
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tarasova_41P_PP
{

using System;
    using System.Collections.Generic;
    
public partial class doctors
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public doctors()
    {

        this.services = new HashSet<services>();

    }


    public int DoctorCode { get; set; }

    public string DoctorName { get; set; }

    public Nullable<int> MedindustryCode { get; set; }



    public virtual medIndustry medIndustry { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<services> services { get; set; }

}

}
