

//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tarasova_41P_PP
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class Tarasova_PPEntities : DbContext
{
    public Tarasova_PPEntities()
        : base("name=Tarasova_PPEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Client> Client { get; set; }

    public virtual DbSet<doctors> doctors { get; set; }

    public virtual DbSet<medIndustry> medIndustry { get; set; }

    public virtual DbSet<services> services { get; set; }

    public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }

    public virtual DbSet<TimeTable> TimeTable { get; set; }

}

}

