
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tarasova_41P_PP
{

using System;
    using System.Collections.Generic;
    
public partial class services
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public services()
    {

        this.Client = new HashSet<Client>();

        this.TimeTable = new HashSet<TimeTable>();

    }


    public int ServicesCode { get; set; }

    public string ServicesName { get; set; }

    public Nullable<int> Price { get; set; }

    public Nullable<int> DoctorCode { get; set; }

    public Nullable<int> MedindustryCode { get; set; }

    public string Image { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Client> Client { get; set; }

    public virtual doctors doctors { get; set; }

    public virtual medIndustry medIndustry { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TimeTable> TimeTable { get; set; }

}

}
