
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tarasova_41P_PP
{

using System;
    using System.Collections.Generic;
    
public partial class TimeTable
{

    public int TimetableCode { get; set; }

    public Nullable<System.DateTime> Date { get; set; }

    public int ServicesCode { get; set; }

    public Nullable<int> Status { get; set; }



    public virtual services services { get; set; }

}

}
